import Link from "next/link";
// import Footer from "@/components/footer";

import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Joshua Michaelson - Portfolio",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body className="min-h-screen bg-black text-gray-200">
        {/* Navigation Bar */}
        <header className="sticky absolute top-0 z-10 bg-gray-900 text-gray-200 py-4">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-xl font-bold">My Portfolio</h1>
            <nav className="space-x-4">
              <Link href="/" className="hover:text-gray-400">
                Home
              </Link>
              <Link href="/projects" className="hover:text-gray-400">
                Projects
              </Link>
              <Link href="/contact" className="hover:text-gray-400">
                Contact
              </Link>
              <Link href="/fun" className="hover:text-gray-400">
                Fun Section
              </Link>
            </nav>
          </div>
        </header>

        {/* Main Content */}
        <main className="w-screen mx-auto">{children}</main>

        {/* Footer */}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
